import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { LandingPageLayout } from "../src/container/LandingPage";

export default function Home() {
  return (
    <div className={styles.containers}>
      <Head>
        <title>GryCare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="http://fonts.cdnfonts.com/css/sofia-pro" rel="stylesheet" />
      </Head>
      <LandingPageLayout />
    </div>
  );
}
